my_string = input('укажите текущую дату: ')
print(type(my_string))
print('моя строка'.upper)
print('моя строка'.lower)
print('my_string'.replace(" ",''))
print(my_string[0])
print(my_string[-1])